### ISSUE TITLE
Otimiza as imagens

### ISSUE THREAD

**Issue by AdrielCavalcante** [GuhPlays/sitegaleria#1]
As imagens do site estão muito grandes. O que gera um lag. Apenas redimensione as imagens.

**Comment by GuhPlays** [comment]
Ok, eu achei que tava lagadinho mas pensei que era meu browser, valeu pela dica. Seu rep ajudou mt no trabalho aqui.

**Comment by AdrielCavalcante** [comment]
De boa : )
Vou fechar essa Issue
